# Generated by Django 2.1.2 on 2018-10-27 19:42

import actas.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_libro', models.SmallIntegerField(default=actas.models.get_last_libro, verbose_name='Número de Libro')),
                ('numero_folio', models.SmallIntegerField(default=actas.models.get_last_folio, verbose_name='Número de Folio')),
                ('numero_acta', models.SmallIntegerField(default=actas.models.get_next_acta, verbose_name='Número de Acta')),
                ('fecha_acta', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Acta')),
                ('descripcion_acta', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descripción del Acta')),
            ],
            options={
                'ordering': ['numero_libro', 'numero_folio', 'numero_acta'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='acta',
            unique_together={('numero_libro', 'numero_folio', 'numero_acta')},
        ),
    ]
