# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-08 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acta', models.DateField(verbose_name='Fecha de Acta')),
                ('numero_acta', models.CharField(max_length=100, unique=True, verbose_name='Numero de Acta')),
                ('numero_folio', models.CharField(max_length=100, unique=True, verbose_name='Numero de Folio')),
                ('numero_libro', models.CharField(max_length=100, verbose_name='Numero de Libro')),
                ('descripcion_acta', models.CharField(max_length=1000, verbose_name='Descripcion del Acta')),
            ],
        ),
    ]
