# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionElectronica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(choices=[('', 'Particular'), ('L', 'Laboral')], max_length=255, verbose_name='Uso')),
                ('observaciones', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Obervaciones')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Direccion de Email',
                'verbose_name_plural': 'Direcciones de Email',
            },
        ),
        migrations.CreateModel(
            name='DireccionPostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(choices=[('', 'Particular'), ('L', 'Laboral')], max_length=255, verbose_name='Uso')),
                ('observaciones', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Obervaciones')),
                ('calle', models.CharField(max_length=255, verbose_name='Calle')),
                ('numero', models.SmallIntegerField(verbose_name='Número')),
                ('piso', models.CharField(blank=True, max_length=5, null=True, verbose_name='Piso')),
                ('departamento', models.CharField(blank=True, max_length=5, null=True, verbose_name='Departamento')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidades.Localidad', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Dirección Postal',
                'verbose_name_plural': 'Direcciones Postales',
            },
        ),
        migrations.CreateModel(
            name='DireccionWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(choices=[('', 'Particular'), ('L', 'Laboral')], max_length=255, verbose_name='Uso')),
                ('observaciones', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Obervaciones')),
                ('direccion', models.URLField(verbose_name='Dirección Web')),
                ('tipo', models.CharField(choices=[('', 'Perfil Web Social'), ('L', 'Pagina Web Laboral')], max_length=255, verbose_name='Tipo web')),
            ],
            options={
                'verbose_name': 'Dirección Web',
                'verbose_name_plural': 'Direcciones Web',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(choices=[('', 'Particular'), ('L', 'Laboral')], max_length=255, verbose_name='Uso')),
                ('observaciones', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Obervaciones')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfonos',
            },
        ),
    ]
