# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionPostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(max_length=1000, verbose_name='Obervaciones')),
                ('calle', models.CharField(max_length=255, verbose_name='Calle')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('piso', models.CharField(blank=True, max_length=5, null=True, verbose_name='Piso')),
                ('departamento', models.CharField(blank=True, max_length=5, null=True, verbose_name='Departamento')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidades.Localidad', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Dirección Postal',
                'verbose_name_plural': 'Direcciones Postales',
            },
        ),
    ]
