# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-21 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergenos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alergeno', models.CharField(max_length=255, verbose_name='Nombre del Alérgeno')),
            ],
        ),
        migrations.CreateModel(
            name='Alergicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Obervaciones')),
                ('alergeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.Alergenos', verbose_name='Alérgeno')),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Bombero', verbose_name='Bombero')),
            ],
        ),
    ]
