# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nombre'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterField(
            model_name='localidad',
            name='codigo_postal',
            field=models.CharField(max_length=255, verbose_name='Codigo Postal'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='localidades.Pais', verbose_name='Pais'),
        ),
    ]
