# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo de Documento')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['abreviatura', 'tipo'],
                'verbose_name': 'Tipo de Documento',
            },
        ),
    ]
