# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-06 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personas', '0001_initial'),
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bombero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto Carnet')),
                ('numero_credencial', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Número de Credencial')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('estado_civil', models.CharField(blank=True, choices=[('Casado', 'Casado/a'), ('Concubino', 'Concubino/a'), ('Divorciado', 'Divorciado/a'), ('Separado', 'Separado/a'), ('Soltero', 'Soltero/a'), ('Viudo', 'Viudo/a')], default='Casado', max_length=255, null=True, verbose_name='Estado Civil')),
                ('lugar_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidades.Localidad', verbose_name='Lugar de Nacimiento')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bomberos', to='personas.Persona', verbose_name='Persona')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bomberos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(unique=True, verbose_name='Año')),
                ('puntaje_en_numero', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Puntaje Numérico')),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bombero_calificacion', to='bomberos.Bombero', verbose_name='Bombero')),
            ],
            options={
                'verbose_name': 'Calificación Anual',
                'verbose_name_plural': 'Calificaciones Anuales',
            },
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título o cargo')),
                ('periodo_desde', models.DateField(verbose_name='Fecha de Inicio')),
                ('periodo_hasta', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descripción')),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomberos.Bombero', verbose_name='Bombero')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Institucion', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Empleo',
                'verbose_name_plural': 'Empleos',
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('P', 'Primario'), ('S', 'Secundario'), ('T', 'Terciario'), ('U', 'Universitario')], default='P', max_length=5, verbose_name='Nivel de Estudio')),
                ('estado', models.CharField(choices=[('F', 'Finalizado'), ('C', 'Cursando'), ('A', 'Abandonado')], default='F', max_length=5, verbose_name='Estado de cursado')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('periodo_desde', models.DateField(verbose_name='Fecha de Inicio')),
                ('periodo_hasta', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descripción')),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomberos.Bombero', verbose_name='Bombero')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Institucion', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('Hermano', 'Hermano/a'), ('Padre', 'Padre'), ('Madre', 'Madre'), ('Hijo', 'Hijo/a'), ('Abuelo', 'Abuelo/a'), ('Nieto', 'Nieto/a'), ('Tio', 'Tío/a'), ('Primo', 'Primo/a'), ('Esposo', 'Esposo/a')], default='Hermano', max_length=255, verbose_name='Parentesco')),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bombero', to='bomberos.Bombero', verbose_name='Bombero')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to='personas.Persona', verbose_name='Familiar')),
            ],
        ),
    ]
