# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fallecido',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Persona')),
                ('fecha_desceso', models.DateField(verbose_name='Fecha de Fallecimiento')),
            ],
            bases=('personas.persona',),
        ),
        migrations.AlterField(
            model_name='bombero',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto Carnet'),
        ),
    ]
