# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
